### ISSUE TITLE
Wrong alleles at Y:28731917 (L405)?

### ISSUE THREAD

**Issue by stephenturner** [genid/Clean_tree2#1]
Hello! I'm looking around at `Clean_tree2`, and I'm encountering issues on a few samples from 1000 Genomes I'm trying to classify. I think I've nailed down where the problem is occurring. The [position 28731917 (L405) in the positions.txt file](https://github.com/genid/Clean_tree2/blob/c44ecfb83484e10c094a557de91c6719273a05c7/data/positions.txt#L828) catalogs this as a C->T mutation. However, in a small number of samples from 1000 Genomes, the allele is actually an **A**. In fact, looking this up in phylotree (L405, alias PF5990, rs9786602) shows that the alleles are A and C. Would a fix be as simple as changing the Ts to As in [this line](https://github.com/genid/Clean_tree2/blob/c44ecfb83484e10c094a557de91c6719273a05c7/data/positions.txt#L828)? 

Thank you!

**Comment by dmontielg** [comment]
Dear Stephen,

Thank you for your comment, there was indeed a problem with this marker, we have updated the position.txt file. That being said we recommend using Yleaf (https://github.com/genid/Yleaf), Clean_tree2 will not be further developed while Yleaf will be. You can also run Yleaf using the position file from Clean_tree2. 

Best,
Diego

**Comment by stephenturner** [comment]
Thanks @dmontielg! I'll definitely take a look at yleaf, and in the meantime, I'll check to see if this solved the issue we were seeing with those 1000G samples. I'll close this issue for now.
